### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by BatoolMM** [nalomran/Learn-Python-In-Arabic#1]
This course looks interesting because the materials were developed in Arabic. However, I think it is way easier for the students to learn python through Jupyter Notebook ( e.g. Goggle Colab) rather than the command line or IDE. Both the command line and IDE look intimidating for people who never programmed before. Please let me know if you needed any help.

**Comment by nalomran** [comment]
Hi Batool,

Thank you for your feedback. I am right now at the phase where I am experimenting with the content and materials of this intro to Python course. I do partially agree with you. However, I do believe that the best way for beginners to learn and experiment with the basic workflow of programming for language like Python is to use and get familiar with the command line i.e know how to (in the simplest form) execute a program, and read and get familiar with basic Python errors. You're right that some may find this intimidating at first but I don't think novice programmers should start off with Jupyter Notebook, in fact I read a couple of articles that support my arguments. For the IDE, they don't have to use an IDE if they don't want to and can use a very simple Editor or the IDE that ships with Python. Everything I've written here is still in the raw form and needs some work but I do appreciate offering help. When I am officially confident with the content of the course, you can fork the repo and do PR to suggest editings, fix, or improve wordings or documentation.
